name: "Docker Image Build"
  
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
    
jobs:
  build:
    runs-on: alpine-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Product Service Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: product-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max